services:
  vault:
    image: hashicorp/vault:latest
    container_name: hashicorp_vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - data:/vault/file
    command: server -dev
volumes:
  data:
