From ubuntu:18.04

Run apt-get update

Run yes | unminimize

Run apt-get update && apt-get install -y apt-utils build-essential cmake sudo vim git

Run apt-get install -y libeigen3-dev

Run apt-get install -y ocl-icd-opencl-dev

Run apt-get install -y software-properties-common

Run add-apt-repository -y ppa:ubuntu-toolchain-r/test

Run apt-get install -y gcc-7 g++-7 gcc-8 g++-8 gcc-9 g++-9 gcc-11 g++-11

Run update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11

Run update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90 --slave /usr/bin/g++ g++ /usr/bin/g++-9 --slave /usr/bin/gcov gcov /usr/bin/gcov-9

Run update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 80 --slave /usr/bin/g++ g++ /usr/bin/g++-8 --slave /usr/bin/gcov gcov /usr/bin/gcov-8

Run update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 70 --slave /usr/bin/g++ g++ /usr/bin/g++-7 --slave /usr/bin/gcov gcov /usr/bin/gcov-7

Run useradd -m -s /bin/bash ice

Run echo "ice:1" |chpasswd

Run usermod -aG sudo ice

USER ice

Workdir /home/ice/cpp_program
