From ubuntu:18.04

Run apt-get update

Run yes | unminimize

Run apt-get install -y curl sudo vim git

Run curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -

Run apt install -y nodejs

Run npm install --global @angular/cli

Run useradd -m -s /bin/bash ice

Run echo "ice:1" |chpasswd

Run usermod -aG sudo ice

Run apt install net-tools

USER ice

Workdir /home/ice

Run git config --global user.email "xwddn1994@gmail.com"

Run git config --global user.name "Wei Xie"

Run ng new newproject --routing

workdir /home/ice/newproject

# Run npm start

# Run ng add @angular/material
