From ubuntu:18.04

Run apt-get update && apt-get install -y apt-utils build-essential cmake sudo vim git

Run yes | unminimize

Run useradd -m -s /bin/bash ice

Run echo "ice:1" |chpasswd

Run usermod -aG sudo ice

USER ice

Workdir /home/ice/cpp_program

Run git config --global user.email "xwddn1994@gmail.com"

Run git config --global user.name "Wei Xie"

