From ubuntu:18.04

Run apt-get update

Run yes | unminimize

Run apt-get install -y curl sudo vim git

Run apt-get install -y python3 python3-pip

Run apt-get install -y cmake

Run useradd -m -s /bin/bash ice

Run echo "ice:1" |chpasswd

Run usermod -aG sudo ice

USER ice

Workdir /home/ice

Run pip3 install numpy scikit-build pandas 
