services:
  jfrog:
    image: releases-docker.jfrog.io/jfrog/artifactory-oss:latest
    container_name: jfrog
    ports:
      - "8081:8081"  # Web UI
    volumes:
      - artifactory_data:/var/opt/jfrog/artifactory
    environment:
      - JF_SHARED_NODE_IP=127.0.0.1

volumes:
  artifactory_data: