services:
  openvpn-as:
    image: openvpn/openvpn-as
    container_name: openvpn-as
    cap_add:
      - NET_ADMIN
    ports:
      - 943:943
      - 443:443
      - 1194:1194/udp
    volumes:
      - openvpn-data:/openvpn
    restart: unless-stopped
  openvpn-data:
