services:
  rabbitmq:
    image: gitlab/gitlab-ce:latest
    container_name: 'gitlab-ce'
    ports:
      - 22:22
      - 80:80
      - 443:443
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
